### PR TITLE
DonaRewards.md

### PR DESCRIPTION
**Pull request by Vman100**
A Dapp for rewarding donators with reward tokens

### CODE REVIEW

**Comment by zettai-caiman** [comment]
@Vman100 

Improvement ideas:
- It is not very clear on why donors will compete against themselves to be the first one to donate. More details on the usability / utility of the rewarded token needs to be addressed. If a donor contributes a large sum at the start, what benefits will they receive in the long run by gaining large sums of DonaRewards tokens?
- Milestones and timed triggers could be an interesting area to look into, do expand more on that section

some requirements:
- there are some typos in your PR, do fix them!

**Comment by Vman100** [comment]
@lerajk I have made changes to my PR

**Comment by zettai-caiman** [comment]
@Vman100 the idea is sound for erc 1973 usability at this point. You can start investigating on the code level. additional ideas:

- bunz token is already working on something similar where you can redeem merchandize for BUNZ, hence this idea is already proven and you don't have to worry about service providers or retail outlets for accepting tokens!
- some more details on milestones / trigger events would be ideal. will there be conditions on when a milestone is triggered? what are such conditions? e.g. 'n'  reward tokens are released at 1st milestone,  'n x 2' for 2nd milestone, 'n x 3' for 3rd milestone and so on. it could also be block numbers - 100 blocks need to be passed before every next milestone

**Comment by Vman100** [comment]
@lerajk I have added a sample of the distribution to PR.

**Comment by Vman100** [comment]
@lerajk  i have added the website link

**Pull request merged**
