### PR TITLE
decentralized-reit.md

### PR DESCRIPTION
**Pull request by abielvillarosa**
Harvest dapp utilizing EIP 1973

### CODE REVIEW

**Comment by zettai-caiman** [comment]
@abielvillarosa 

improvement ideas:
- computation is costly in the ETH network, when users withdraw the capital (shares + dividends) you may encounter some problems on computing the overall rewards for each participant. I suggest you look into this closely as ERC 1973 doesn't help much with it
- REIT could be a good use case because investors make the most when they get in early with the right project. it is important to set these rules in the application clearly on reward distribution over time
- you can look into erc 1400 security token standard and get more ideas, that could be more applicable than erc 20

some requirements:
your file is named as Create harvest.md, i believe you meant harvest.md?
to clarify: additional notes section is for your project not for ERC 1973

**Comment by abielvillarosa** [comment]
Updated deReit.md based on your comments. The rewards given is changed to simple rewards to entice investors on the inital years of operation instead of the dividends which requires computation. This will be a better use case of the EIP1973.

**Comment by zettai-caiman** [comment]
@abielvillarosa very sound application at this stage. I think the idea is ready to be investigated on a code level. Some more areas for you to think about as you build your crypto economic environment:

- are there any barriers to entry to be a participant? maybe there could be a stake/fees amount. e.g. a minimum of 1 eth is required to be a participant. every 6 months this fees can be doubled, so at later stages the shares distributed are same (100,000) but the barrier to entry is higher and the rewards allocated lower
- there should be some rules on how one can be a participant, without such rules same people could have multiple addresses and buy more shares. at a later stage these people will dump their shares and destroy the network. with this application a form of KYC is essential. 
- you can think of whitelisting addresses, explore ENS for authentic buyers

**Comment by DevSlashNull** [comment]
@abielvillarosa: This is a great start, and a fantastic idea. I think that @lerajk has some solid suggestions for improvement, and I'm looking forward to seeing how you flesh out the mechanics and cryptoeconomics of it in code. Please also update your deREIT.md with your project's Git repo once you create it and start coding.

**Comment by abielvillarosa** [comment]
Added code implementation for final pull request

**Pull request merged**
